### PR TITLE
ffh.dhcp_server: switch to dnsmasq

### PR DESCRIPTION
**Pull request by CodeFetch**
dnsmasq is familiar to us, better maintained than Kea and does not
cause the bug mentioned in issue #109.

### CODE REVIEW

**Comment by CodeFetch** [comment]
Works on sn06, but I think we have the same problem with the batman race condition here as it fails when booting sometimes and only gets started by the gateway_announcement.sh script (by the way I think the old one failed, too).

**Comment by Manawyrm** [comment]
> Works on sn06, but I think we have the same problem with the batman race condition here as it fails when booting sometimes and only gets started by the gateway_announcement.sh script (by the way I think the old one failed, too).

This sounds a bit like the behaviour caused by `--bind-interfaces` (in the systemd service). I think you should be able to remove it completely. 
`bind-interfaces` used to be a workaround to strictly bind only on a specific interface. The default behaviour is a bit better.
Otherwise `--bind-dynamic` might be helpful?

**Comment by CodeFetch** [comment]
@Manawyrm I've read the man-page, but I don't share the concerns. From my point of view it reduces pitfalls and increases performance. Maybe you can enlighten me what the cons are...

**Comment by CodeFetch** [comment]
@Manawyrm Giving it a second thought I think it does not make a difference performance-wise. Furthermore binding to the interfaces causes problems, because the Batman interfaces are in a dirty state. So I'll change that.

**Comment by Manawyrm** [comment]
bind-interfaces will not bind to [::]:69 (aka wildcard), instead it binds to the specific interfaces directly. 
I don't see why this would increase performance. Only advantage would be the ability to run other DHCP servers on different interfaces. 

bind-interfaces is only handled at startup, which leads to the race condition behaviour.  
You could either disable bind-interfaces (which would bind a wildcard listen and work fine) or use bind-dynamic (which would use netlink messages to get informed when a change occures and will then start to listen on the newly established interfaces by batman). 

I would personally drop the bind-interfaces altogether, I see no reason for using it.

**Comment by CodeFetch** [comment]
> Only advantage would be the ability to run other DHCP servers on different interfaces.

We are planning to run ddhcp in parallel. So maybe I should leave it as is. I've added the ugly wait_for_iface-hack...

**Comment by Manawyrm** [comment]
> We are planning to run ddhcp in parallel. So maybe I should leave it as is. I've added the ugly wait_for_iface-hack...
ddhcpd? 
It only runs on the gluon nodes directly, not on the supernodes. So you can just ignore that.

**Comment by CodeFetch** [comment]
@Manawyrm The idea was to run DDHCP on the supernodes for the nodes that do not run DDHCP themselves (devices where the autoupdater is disabled or where we don't ship updates like tiny).

**Comment by Manawyrm** [comment]
Then you'd replace dnsmasq with it completely. Running 2 DHCP servers on the same interface isn't going to help you much :smile: 
You could start to switch single domains over to ddhcpd from dnsmasq, but I'm not sure if that's very useful.

**Comment by CodeFetch** [comment]
> You could start to switch single domains over to ddhcpd from dnsmasq, but I'm not sure if that's very useful.

Exactly that. We are going to use dom99 as a testing domain for rolling WireGuard+Batman V+DDHCP.

**Comment by Manawyrm** [comment]
Then I'd recommend using bind-dynamic. :)

**Comment by CodeFetch** [comment]
@Manawyrm I don't want it to dynamically add interfaces. Why should I add it?

**Comment by TobleMiner** [comment]
> @Manawyrm The idea was to run DDHCP on the supernodes for the nodes that do not run DDHCP themselves (devices where the autoupdater is disabled or where we don't ship updates like tiny).

I'd advise against running ddhcpd on supernodes. It is not designed for that sort of use. The high amount of leases used and discarded on the supernode will lead to a large amount of multicast management traffic from that single node which could be avoided easily.Just run a normal DHCP server with a separate DHCP range on them please.

**Comment by Manawyrm** [comment]
> Why should I add it?

Combines the benefits of bind-interfaces with the benefits of not binding any interfaces :) 
Only "downside" is that it only works on Linux, but that's totally fine for us.

**Comment by 1977er** [comment]
Can we please stick to one technology instead of hopping around whenever we find a missing comma in the documentation? There will never be a perfect solution. Evaluating possible alternatives is good BEFORE deciding on a candidate and implementing it. Anything else causes frustration and should be avoided unless there are good reasons for it.

**Comment by Manawyrm** [comment]
My view on things: 

```
Kea DHCP: 
+ modern
+ can handle large setups fine
- not included in a recent version in Debian stable

dnsmasq:
- does not handle large installation well (sort of okay with ram disks)
- bad security track record

ddhcpd: 
+ runs directly on the gluon nodes
+ quick response times
- needs secondary fallback DHCP for old nodes/without autoupdater

isc dhcp: 
- old
- suffers from the DHCP issues shown in #109
```

I'd recommend Kea + ddhcpd, Kea alone will probably work fine as well.

**Comment by CodeFetch** [comment]
> I'd advise against running ddhcpd on supernodes. It is not designed for that sort of use. The high amount of leases used and discarded on the supernode will lead to a large amount of multicast management traffic from that single node which could be avoided easily.Just run a normal DHCP server with a separate DHCP range on them please.

@TobleMiner Then that's something we should fix in my opinion. I've looked at the code and I share your concerns.

**Pull request closed without merging**
