### PR TITLE
sn01: change ips to new spaces

### PR DESCRIPTION
**Pull request by AiyionPrime**
This is currently deployed on ns01 as well as sn01 and appears not to work, yet.

Existing fastd connections work;
new ones can not establish a connection. Me and @1977er lack proper testdevices...

I just pinned a remote device to sn01 and rebooted it; wont come back online.

### CODE REVIEW

**Comment by AiyionPrime** [comment]
Here's the router in question...
https://hannover.freifunk.net/karte/#/en/map/7cff4de6c44f

**Comment by AiyionPrime** [comment]
connection to other nodes still established, even after reboot. Something's fishy.

**Comment by AiyionPrime** [comment]
well:
> Feb 20 15:25:15 sn01 fastd@mesh_fastd_18[1015]: bound to 185.197.132.140:10018

**Comment by AiyionPrime** [comment]
default ip4 was still set to 140, and is not anymore, after reboot, I suppose.
rerunning sn01.

**Comment by AiyionPrime** [comment]
fastd is reestablished

**Comment by AiyionPrime** [comment]
respondd responds again :)

**Comment by AiyionPrime** [comment]
rolling out changes to other supernodes in order to rebuild gre tunnels.

**Comment by AiyionPrime** [comment]
get rid of the .140 to clean up /etc on sn01

**Review by 1977er — APPROVED** [review]

**Comment by AiyionPrime** [comment]
I am done here, this resolved a lot in #82.
I'm going to merge this, as its tested and already rolled out.

**Pull request merged**
