### PR TITLE
Update mesh announce

### LINKED ISSUE #146: respondd not running on sn01
I just saw this in the log: 
```
Feb 13 20:53:18 sn01 respondd.py[825]: usage:
Feb 13 20:53:18 sn01 respondd.py[825]:       respondd.py -h
Feb 13 20:53:18 sn01 respondd.py[825]:       respondd.py [-f <configfile>] [-d <dir>]
Feb 13 20:53:18 sn01 respondd.py[825]: respondd.py: error: unrecognized arguments: -i bat10 -b bat10 -i mesh_fastd_10 -i bat11 -
```

### PR DESCRIPTION
**Pull request by AiyionPrime**
This closes #146 

More details in commit messages of PR-commits;

Basically upstream implemented https://github.com/ffnord/mesh-announce/pull/60 .
We pulled from their master and broke our config.
This does not happen often; I'd vote for not changing the repos upstream because of this.

### CODE REVIEW

**Comment by AiyionPrime** [comment]
Reviews are requested; I'll merge this today at around 18:00 as our current state is broken; and this wont break it more.

Tested on sn07:
https://hannover.freifunk.net/karte/#/en/map/88e640ba7021

**Comment by AiyionPrime** [comment]
Tested on sn01 as well.

**Comment by AiyionPrime** [comment]
Will go on with 08 later to test for stretch issues.

**Review by 1977er — APPROVED** [review]
Just out of curiosity: why is the service called respondd, but the software is called mesh-announce?

**Comment by AiyionPrime** [comment]
Because mesh-announce provides the capabilities of respondd.
It's the same with your dhcp service.
Kea provides dhcpd, so the service is called dhcpd, becuase any sysadmin who'll come along would suffer alot if he'd to find out first, which dhcp server is currently used.

The pattern is furthermore neat, as it makes conflicting providing services more obvious; hence try having two programs providing the same service dhcpd or respondd.

In this provide-structure respondd or dhcpd are more or less standardized interfaces.

**Comment by 1977er** [comment]
Bad example. ;) Just yesterday it took me some time to find out, that its a bad idea to go against the package mantainer. Long story short: its isc-kea-dhcp4-server again.

I see your point, but I think its more helpful/intuitive when all components (process name, config file, paths etc) of a software share the same name.

**Review by lemoer — APPROVED** [review]
LGTM. Can be merged.

**Comment by AiyionPrime** [comment]
Not a bad example, just not considered. If your PM deploys it as kea, it's kea.
But the PM for mesh-announce calls it respondd, so I won't rename this, sorry.

**Comment by 1977er** [comment]
I did not want you to rename it. I was just curious. :)

**Comment by AiyionPrime** [comment]
rolled out successfully on all supernodes

**Pull request merged**
