### PR TITLE
ffh.supernode: delete old GRE interfaces

### LINKED ISSUE #76: killing gre tunnels
Apparently restarting networkd is not enough, in case the configuration of a gre tunnel changed in terms of its address.

I'd add a new step to ffh.exitnode tasks/gre.yml that checks, if a gre interface config changed in the previous step and then deletes the corresponding interface, if it exists.

That step should then perform a series of commands for the if:
```
ip link set down $grename
ip link del dev $grename
```
If no interface changed, there is no need to restart networkd.

The same should happen for the supernode role.

### PR DESCRIPTION
**Pull request by CodeFetch**
Makes sure the new configuration is applied (closes #76).

### CODE REVIEW

**Comment by AiyionPrime** [comment]
tested on sn07, works.
Looks a little weird if the interface is alread gone;

If one sets up the server for the first time, there's a huge red message; not sure how @1977er feels about that.

**Review by 1977er — APPROVED** [review]
If the big red message is followed by a unicorn, it's okay.

**Comment by AiyionPrime** [comment]
Can't do.

**Comment by AiyionPrime** [comment]
I'll merge this around 18:00. Any objections?

**Comment by lemoer** [comment]
Go ahead

**Pull request merged**
