### PR TITLE
Feature ffh chosen gw sh drop sysfs

### LINKED ISSUE #129: ffh_chosen_gw.sh depends on deprecated /sys/class/net/bat
ffh.cli_tools/files/bin/ffh_chosen_gw.sh

```node_id_prefix=$(cat /sys/class/net/bat10/address | cut -d ':' -f 1-3 | tr -d ':')..$(cat /sys/class/net/bat10/address | cut -d ':' -f 5 | tr -d ':')```

### PR DESCRIPTION
**Pull request by AiyionPrime**
This closes #129 and depends on awk.

### CODE REVIEW

**Comment by AiyionPrime** [comment]
Sorry, this contains a wrong commit.

**Comment by AiyionPrime** [comment]
Better.

**Review by 1977er — COMMENTED** [review]
Dunno what this script is used for. Dunno if it is harmful to hardcode bat10. The transition to awk looks ok.

**Comment by AiyionPrime** [comment]
bat10 could be replaced by "the first bat interface" or even "any bat interface".
It's just about the first three mac-adress bytes

**Comment by 1977er** [comment]
You have my blessing. ;)

**Comment by AiyionPrime** [comment]
/sys/class/net/bat does still exist, even with batman 2021.0. No need to fix this.

**Pull request closed without merging**
