### PR TITLE
Feature gateway announcement drop sysfs dependency

### LINKED ISSUE #124: gateway_announcement.sh depends on deprecated /sys/class/net/bat
/sys/class/net/bat was removed in batman-2021.

### PR DESCRIPTION
**Pull request by AiyionPrime**
This closes #124 and depends on awk.

Is tested on sn07

### CODE REVIEW

**Comment by AiyionPrime** [comment]
@lemoer I'm not sure, if I misunderstood /sys/class/net for some reason there are no bat interfaces on sn07 using `ip a`.

Something is weird over there, not sure if thats related, I'm tired.

**Review by 1977er — APPROVED** [review]
Not sure why there are no bat devices on sn07, but this replacement looks good.

**Comment by AiyionPrime** [comment]
ecsv just hinted a different approach which would be `ip link show type batadv`.
This would really address all all bat devices and not anything that is called like one.
I'm not sure what's the better approach, maybe @lemoer has an opinion on that?

**Comment by AiyionPrime** [comment]
/sys/class/net/bat does still exist, even with batman 2021.0. No need to fix this.

**Pull request closed without merging**
