### PR TITLE
Replace ISC dhcp4-server with isc-kea-dhcp4-server

### PR DESCRIPTION
**Pull request by 1977er**
My very first PR.

### CODE REVIEW

**Comment by AiyionPrime** [comment]
I just looked into it;
with kea it should finally be easy enough to omit the dhcp leases in logs at all.

in the [configuration docs ](https://kea.readthedocs.io/en/kea-1.8.0/arm/config.html) is a topic about how to assign log levels to log topics like this:
```
"loggers": [{
            "name": "*",
            "severity": "DEBUG"
        }]
```

The loggers are then listed in the [logger section](https://kea.readthedocs.io/en/kea-1.8.0/arm/logging.html#id3).
The ones we care for are `kea-dhcp4.leases` and possibly `kea-dhcp6.leases`.

Their severity can be set to log-level `NONE` as stated [here](https://kea.readthedocs.io/en/kea-1.8.0/arm/logging.html#the-severity-string-logger).

I'd really like to see us making use of this great feature as it would get rid of #70, finally.

Please let me know what you think about this opportunity.

**Comment by 1977er** [comment]
The current proposed config logs events with a severity of WARN and above. Afaik lease information are already left out. I will keep an eye on it while deploying the first (test) installations.

I would not recommend turning off logging at all (loglevel NONE).

**Comment by 1977er** [comment]
Tested on sn01. Seems to work fine.

**Comment by lemoer** [comment]
Does this mean, it has been rolled out on all supernodes?

**Comment by 1977er** [comment]
Nope. Only on sn01 so far.

**Comment by 1977er** [comment]
On the hardly used sn01 we get a handful of "kea-dhcp4[XXX]: ERROR [kea-dhcp4.packets.140175791149824] DHCP4_BUFFER_RECEIVE_FAIL error on attempt to receive packet: Truncated DHCPv4 packet (len=0) received, at least 236 is expected." messages per day. We might want to silence them with mailfilters in the journald role.

**Comment by AiyionPrime** [comment]
Please keep in mind, that I role out master on our supernodes on a regular basis.
I always assume master is tested and safe to deploy.

It's not really an option to keep in mind which tags are safe to deploy and which aren't.

**Comment by CodeFetch** [comment]
@AiyionPrime I actually thought that we should roll out the change on all supernodes. I think that rolling the change out on a single supernode does not really help in finding issues... That's something we could have done if we'd have a parallel test network as 1977er suggested.

@1977er To me it looks quite stable. At least as stable as ISC. So shall we roll it out everywhere or shall we modify the Playbooks and restore the old dhcp-role as "legacy_dhcp" or something and use it for the supernodes running ISC DHCP?

**Comment by 1977er** [comment]
When rolling out KEA: deinstallation of legacy isc-dhcpd was not in the scope of this role and has to be done manually.
Should be done by night when fewer endusers are affected.

**Comment by AiyionPrime** [comment]
isc-dhcp-server is the one to be removed,
isc-dhcp-common contains manpages for both server and client and is irrelevant;
what ever isc-dhcp-client does in our system, I left it where it was on both sn07 and sn09.

**Comment by 1977er** [comment]
I assumed isc-dhcp-client ships dhclient which is partially used on some systems to get ip addresses for eth0 from ISPs. There I did not touch that one.

**Comment by 1977er** [comment]
This PR is already merged and targets a removed package now. Can we close and remove it?

**Comment by AiyionPrime** [comment]
I did not intend to reopen it, just thought this would be a good place to discuss the manual migration strategy.

**Pull request merged**
